# Generated by Django 3.2.4 on 2021-07-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expires',
            new_name='expires_in',
        ),
    ]
